### ISSUE TITLE
Is 'RemoteForward' in .ssh/config in exercises correct?

### ISSUE THREAD

**Issue by carpdiem** [missing-semester/missing-semester#31]
As described in the Remote Machines exercises, including the line
`RemoteForward 9999 localhost:8888`
in your .ssh/config fails silently on my machine.

In particular, with this setup, even running `netstat -tln` from the host machine does not show anything listening on localhost:9999.

However, if you change the .ssh/config to:
`LocalForward 9999 localhost:8888`
Everything works perfectly.

Can the RemoteForward be correct? I've been trying to dig into this for hours and cannot find any way to make it work, even with significant manual trials using ssh -R

**Comment by anishathalye** [comment]
Thank you for pointing this out -- fixed in 5172ab6d4888a883cdaf1f277efc0adb4a5ea99f!

`RemoteForward` / `ssh -R` is a valid argument, which is why it "fails silently" -- it's just doing the wrong thing. It's basically the opposite of `LocalForward`; doing `RemoteForward xxxx:host:yyyy` forwards port `xxxx` on the machine you've SSHed into to `host:yyyy` on the local machine. What we want in the exercise is indeed `LocalForward` (and I think in general, `LocalForward` is the more commonly used feature).
