### ISSUE TITLE
Debugging and Profiling "This is red" isn't working

### ISSUE THREAD

**Issue by nickycutesc** [missing-semester/missing-semester#85]
Noticing that this section within the "Debugging and Profiling" lecture (https://missing.csail.mit.edu/2020/debugging-profiling/) isn't working:

For example, executing echo -e "\e[38;2;255;0;0mThis is red\e[0m" prints the message This is red in red on your terminal.

I provided an alternative command which was taken from here: https://stackoverflow.com/a/57559997/4962467

The first command is from the lecture and the second command is the solution from Stack Overflow:
<img width="573" alt="image" src="https://user-images.githubusercontent.com/24903257/87212306-cff0f680-c2eb-11ea-87fa-cc58cd6a63ab.png">

Am I inputting the lecture command into my terminal prompt incorrectly?

**Comment by anishathalye** [comment]
Thanks for opening the issue. This is happening because macOS's Terminal.app doesn't support 24-bit color escape codes. I've updated the notes in da9e6585e2cbf5a82b3783d014c5e643ed1e20d0 to point this out.

By the way, I recommend switching to a more powerful terminal application like [iTerm2](https://www.iterm2.com/).
